### PR TITLE
:bug: [#4403] Fix submission PDF layout for empty values

### LINKED ISSUE #4403: PDF formatting broken
### Product versie / Product version

2.5.9

### Customer reference

SWO 25

### Omschrijf het probleem / Describe the bug

#4327 seems to have caused more issues then predicted. 

image

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by stevenbal**
previously, empty values did not take up any space, breaking the submission PDF layout if any fieldsets were used or if fields did not have data

Closes #4403 

**Changes**

* Fix submission PDF layout for empty values

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

**Comment by stevenbal** [comment]
Generated PDF before fix:
Screenshot from 2024-06-18 13-41-26

PDF after fix:
Screenshot from 2024-06-18 13-40-51

**Comment by stevenbal** [comment]
PDF before fix
Screenshot from 2024-06-18 13-49-21

and after fix

Screenshot from 2024-06-18 13-48-59

**Review by sergei-maertens — APPROVED** [review]
that's a quick fix!

**Comment by sergei-maertens** [comment]
Backports:

* 2.6.x: 69bddb9fcdfff7963cad53f341565690129e93bf
* 2.5.x: 20fab4228f85da6c5f7524419ff0a3b64275e517
* 2.4.x: 901d4e1f9499cb56f56739480b3832442744ef93

**Pull request merged**
