### PR TITLE
Fix hidden component validation blocking submission completion

### LINKED ISSUE #4065: Hidden fields/components are not ignored/skipped for backend input validation
Taiga HLM 107

Example response data from `_complete` endpoint:

```json
{
    "type": "https://testformulieren.haarlemmermeer.nl/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:4967d426-873b-4c14-b5e3-881ca47eac81",
    "invalidParams":
    [
        {
            "name": "steps.0.data.alternatiefAdres",
            "code": "required",
            "reason": "Dit veld is vereist."
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by sergei-maertens**
Closes #4065

### CODE REVIEW

**Review by vaszig — COMMENTED** [review]
I would approve this since the changes seem to be reasonable to me. The failing tests though make me wondering what is exactly wrong.

**Comment by sergei-maertens** [comment]
> I would approve this since the changes seem to be reasonable to me. The failing tests though make me wondering what is exactly wrong.

Flaky tests that show up every once in a blue moon... :(

**Comment by vaszig** [comment]
> > I would approve this since the changes seem to be reasonable to me. The failing tests though make me wondering what is exactly wrong.
> 
> Flaky tests that show up every once in a blue moon... :(

Ok, I hadn't seen them before..

**Review by vaszig — APPROVED** [review]

**Comment by sergei-maertens** [comment]
Backport: 3d985756d55737ed4b16c283a4c2a835abd5b604 (only 2.6.x is affected)

**Pull request merged**
