### PR TITLE
🐛 Fix validation in `ZaakOptionsSerializer`

### PR DESCRIPTION
**Pull request by Viicos**
Part of https://github.com/open-formulieren/open-forms/issues/3553

For some context: https://github.com/open-formulieren/open-forms/pull/3146#discussion_r1228246353

When no ZGW API set is configured, we would get a `KeyError` in `RoltypeOmschrijvingValidator`, because it was running before `validate`:

https://github.com/open-formulieren/open-forms/blob/66d9beea7aaa6eaa1737aec30a40ac1d2416e04f/src/openforms/registrations/contrib/zgw_apis/plugin.py#L72-L90

By providing a default value, it will be used by `RoltypeOmschrijvingValidator` if not provided by the user.

---

~~Looking at the admin frontend, a json schema rendered form is used (dynamically), and error handling doesn't seem to work, hence the https://github.com/open-formulieren/open-forms/issues/3553 issue.~~ Seems to work:
image

### CODE REVIEW

**Review by sergei-maertens — COMMENTED** [review]
this behaviour is not compatible, is it? because once it obtains the default, it's configured at the form level which ZGW API group to use, but if you then change the global configuration default, existing forms are still pointing to the old record.

**Comment by Viicos** [comment]
> if you then change the global configuration default, existing forms are still pointing to the old record.

Ok now I understand the wanted behaviour (this also explains why `validate` would only check if a default api group was available, but it would not alter `attrs` before returning it)

**Comment by Viicos** [comment]
The usage of `get_zgw_config` might feel a bit hacky, but couldn't find any better solution

**Comment by Viicos** [comment]
Now regarding the original issue, we can still get 500 errors if requesting the catalogi client fails (due to `response.raise_for_status()`).

Should we catch them and throw a generic `ValidationError` (_something went wrong when checking catalogi blabla_), or give more info about the catalogi error in the validation error description?

**Comment by sergei-maertens** [comment]
> Now regarding the original issue, we can still get 500 errors if requesting the catalogi client fails (due to `response.raise_for_status()`).
> 
> Should we catch them and throw a generic `ValidationError` (_something went wrong when checking catalogi blabla_), or give more info about the catalogi error in the validation error description?

An HTTP 4xx status code doesn't make sense here, because it's not a client error (the client cannot change their call to make it pass), so leaving it a HTTP 500 is fine.

What we can do instead is a similar approach to the SDK - have a generic error boundary that gets information about the status code and show a (more) appropriate message. However, that's too big of a scope for this ticket, it requires quite a bit of restructuring and there is a redesign planned, so I think we should keep that thought as a requirement for the new design.

**Comment by Viicos** [comment]
> An HTTP 4xx status code doesn't make sense here, because it's not a client error (the client cannot change their call to make it pass), so leaving it a HTTP 500 is fine.

Yes apart from a 404 error, this makes sense (and I don't think a 404 could ever happen considering we are making a list request, so if query params are wrong it will simply return a 200 with an empty list).

So if this is out of scope I think this PR is ready for review

**Review by sergei-maertens — APPROVED** [review]
Rebase on master to check the CI failures resolution, then we can merge this

**Pull request merged**
