### PR TITLE
:lipstick: [#1077] Fix admin help text hover

### PR DESCRIPTION
**Pull request by stevenbal**
fixes: #1077

### CODE REVIEW

**Comment by stevenbal** [comment]
Fixed the help text hover:
Screenshot from 2021-12-13 17-14-33

**Comment by sergei-maertens** [comment]
We had made a start using a popover library and this patch probably breaks
the style in other places as this is what's included in default project I
believe

**Comment by sergei-maertens** [comment]
@joeri can you validate this, I think you originally made these styling setups?

**Comment by joeribekker** [comment]
Made some improvements with what we have.

**Review by joeribekker — APPROVED** [review]

**Pull request merged**
