### PR TITLE
Fix/new logo e idas

### PR DESCRIPTION
**Pull request by nikkiysendoorn1**

### CODE REVIEW

**Comment by nikkiysendoorn1** [comment]
Closes #3957

**Review by SilviaAmAm — APPROVED** [review]

**Review by Viicos — APPROVED** [review]
Was there any issue with the svg logo?

**Comment by nikkiysendoorn1** [comment]
@Viicos Yes, the SVG only worked on the mobile device, because there was missing some styling. So I can also add the SVG and then add some styling? What do you prefer?

**Comment by Viicos** [comment]
> @Viicos Yes, the SVG only worked on the mobile device, because there was missing some styling. So I can also add the SVG and then add some styling? What do you prefer?

Was just wondering what was the issue with the svg; I think it's fine to have a png for such a small icon (and svgs can be tricky with styling so I don't think it's worth spending time on it)

**Pull request merged**
