### PR TITLE
Refactor validation plugins

### PR DESCRIPTION
**Pull request by Viicos**
Part of #3607
Depends on #3646

### CODE REVIEW

**Comment by sergei-maertens** [comment]
It looks like there are some commits included here that shouldn't, e.g. all the addressNL related commits?

**Comment by Viicos** [comment]
This was checked out from [feature/3607-brk-validator](https://github.com/open-formulieren/open-forms/tree/feature/3607-brk-validator). If merged, GH will automatically rebase this branch onto `master`, making the addressNL related commits "disappear". Do you want to handle this another way?

**Comment by sergei-maertens** [comment]
> This was checked out from [feature/3607-brk-validator](https://github.com/open-formulieren/open-forms/tree/feature/3607-brk-validator). If merged, GH will automatically rebase this branch onto `master`, making the addressNL related commits "disappear". Do you want to handle this another way?

But both that PR and this one have the exact same set of commits.

I was under the impression that a validator refactor PR would be based on master, apply the refactor and then the BRK validator PR would be rebased on that result where the new validator is then added. I'm very confused now.

**Comment by Viicos** [comment]
> But both that PR and this one have the exact same set of commits.

This PR has the following extra commit: https://github.com/open-formulieren/open-forms/pull/3701/commits/4e0293a1c300674221bf5908c6afa6a4a522b834

> I was under the impression that a validator refactor PR would be based on master, apply the refactor and then the BRK validator PR would be rebased on that result where the new validator is then added. I'm very confused now.

The issue is some refactor was already done in the BRK PR, namely having the submission being passed in in validators. Having the refactor based on `master` would imply to duplicate work with this submission being passed in.

**Comment by sergei-maertens** [comment]
Ah, both have 17 commits but only commits 17 are different, I see now.

Okay, I've marked it as draft so that the other PR can be sorted out first.

**Comment by Viicos** [comment]
Superseded by https://github.com/open-formulieren/open-forms/pull/3741

**Pull request closed without merging**
