### PR TITLE
Update NUM_PROXIES default

### PR DESCRIPTION
**Pull request by SilviaAmAm**

### CODE REVIEW

**Review by sergei-maertens — CHANGES_REQUESTED** [review]
The default of `1` is correct, however please update the dev settings with `os.environ.setdefault("NUM_PROXIES", "0")`

**Comment by SilviaAmAm** [comment]
But now the default in base.py is `0` (in the docker.py it is `1`). Should I still add `os.environ.setdefault("NUM_PROXIES", "0")` to dev.py?

**Comment by joeribekker** [comment]
In retrospect, I think the default should be 1 and only dev should be 0.

**Comment by SilviaAmAm** [comment]
Okay, i will update both!

**Review by sergei-maertens — APPROVED** [review]

**Pull request merged**
