### PR TITLE
[#2166] Modified Dockerfile with Volumes hint to prevent writing to container layer

### LINKED ISSUE #2166: Modify Dockerfile with Volumes hint
### Thema / Theme

Other

### Omschrijving / Description

Modify dockerfile like Open-Zaak https://github.com/open-zaak/open-zaak/blob/main/Dockerfile#L66

### Added value / Toegevoegde waarde

_No response_

### Aanvullende opmerkingen / Additional context

_No response_

### PR DESCRIPTION
**Pull request by Bartvaderkin**
Fixes #2166

### CODE REVIEW

**Comment by Bartvaderkin** [comment]
@sergei-maertens @SilviaAmAm I don't see an `/app/log` volume in the deployment https://github.com/open-formulieren/open-forms/blob/e64c9368264d3f662542866e2d7d5ba15e0f265c/deployment/app.yml#L39

**Comment by Bartvaderkin** [comment]
Also don't see a log volume in the docker-compose but that's probably intentional for development. https://github.com/open-formulieren/open-forms/blob/master/docker-compose.yml

**Comment by sergei-maertens** [comment]
> @sergei-maertens @SilviaAmAm I don't see an `/app/log` volume in the deployment, is this as expected?
> 
> https://github.com/open-formulieren/open-forms/blob/e64c9368264d3f662542866e2d7d5ba15e0f265c/deployment/app.yml#L39-L48

yes - on docker we log to `stdout` in the django settings (see https://github.com/open-formulieren/open-forms/blob/master/src/openforms/conf/base.py#L433), but if we forget this with a new logger or make a mistake, then there's a chance logs go to `/app/log`. If there's no explicit volume mount made there, then the container runtime will create one and manage that lifecycle.

**Comment by sergei-maertens** [comment]
for the failing tests - we probably need to enable buildkit in CI. Locally I have the following envvars:

```
COMPOSE_DOCKER_CLI_BUILD=1
DOCKER_BUILDKIT=1
```

**Comment by sergei-maertens** [comment]
> Also don't see a log volume in the docker-compose but that's probably intentional for development. https://github.com/open-formulieren/open-forms/blob/master/docker-compose.yml

Feel free to add it, it can't hurt and it serves as a good reminder for people building Helm charts based on docker-compose as a reference.

**Comment by Bartvaderkin** [comment]
I made the changes to this repo, and send a PR proposal for Ansible to our SaaS deployment repos.

**Review by sergei-maertens — APPROVED** [review]

**Pull request merged**
