### PR TITLE
[#1076] Added regex to postcode component

### LINKED ISSUE #1076: Postal Code field does not apply validation
Issue raised by gemeente Den Haag (Taiga 178)

It seems that the postal code field does not apply validation. An incomplete value can be entered, and the formstep can still be submitted:

image

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #1076 

Add regex to postcode component

Frontend PR: https://github.com/open-formulieren/open-forms-sdk/pull/161

### CODE REVIEW

**Review by sergei-maertens — APPROVED** [review]
I'm curious where this regex comes from - can you add a documentation link perhaps?

**Comment by SilviaAmAm** [comment]
It comes from here: https://stackoverflow.com/a/17898538/7146757 :sweat_smile: Plus https://nl.wikipedia.org/wiki/Postcodes_in_Nederland to check that SS, SA and SD are really not used :sweat_smile: 
Should I add this anyway?

**Comment by sergei-maertens** [comment]
Yeah, add them as comments. I had a hunch there was a reason for SA/SS/SD not being used because of the Nazi-association, but this might not be obvious to everyone.

**Comment by SilviaAmAm** [comment]
@sergei-maertens Comment added :)

**Review by sergei-maertens — APPROVED** [review]

**Pull request merged**
