### PR TITLE
Typefout verbeterd.

### PR DESCRIPTION
**Pull request by fluteijn-utrecht**
Closes #...

**Changes**

[Describe the changes here]

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [ ] Checked copying a form
  - [ ] Checked import/export of a form
  - [ ] Config checks in the configuration overview admin page
  - [ ] Problem detection in the admin email digest is handled

- Release management

  - [ ] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [ ] Ran `./bin/makemessages_js.sh.sh`
  - [ ] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [ ] Commit messages refer to the relevant Github issue
  - [ ] Commit messages explain the "why" of change, not the how

### CODE REVIEW

**Review by sergei-maertens — APPROVED** [review]

**Comment by sergei-maertens** [comment]
Thanks for all the documentation fixes :heart: !

**Comment by sergei-maertens** [comment]
I've squashed and merged this :) for future PRs, can you please avoid merging the master branch into a feature/bugfix branch and prefer rebasing instead? That helps keep our commit history clean/more linear!

**Comment by fluteijn-utrecht** [comment]
I'm sorry, I will do this.

**Comment by sergei-maertens** [comment]
No worries, we appreciate the contributions a lot!

**Pull request merged**
