### PR TITLE
:lipstick: increase bottom banner

### PR DESCRIPTION
**Pull request by jiromaykin**
Increase banner distance on bottom for all screen sizes.
Fixes  open-formulieren/open-forms#2549

### CODE REVIEW

**Review by sergei-maertens — APPROVED** [review]
It does the job for now :grimacing:

**Comment by LaurensBurger** [comment]
7rem on mobile is still overlapping:
image

**Comment by jiromaykin** [comment]
> 7rem on mobile is still overlapping

Oh bummer, @LaurensBurger did you do a hard refresh? We may need to re-open this issue. None of my browsers show this much overlap in mobile view (I've checked in Firefox, Chrome + Brave on Linux).

**Comment by LaurensBurger** [comment]
@jiromaykin i think there is something else causing it to overlap with your fix - there is a whitespace on some devices, just underneath the footer. This whitespace probably takes away from the 7rem. 
image

**Pull request merged**
