### PR TITLE
:whale: [#2978] -- Fix podman incompatibility.

### LINKED ISSUE #2978: Dockerfile does not build in rootless docker alternative "Podman"
### Product versie / Product version

2.1.1

### Omschrijf het probleem / Describe the bug

The Dockerfile does not work with Podman, an alternative to Docker that is rootless and used at a customer of Open Forms. The main issues seems to be that certain `VOLUME`/`COPY` instructions result into permissions being set to the root user, which can be mitigated by setting the `USER` earlier in te process and passing the `--chown=maykin` flag to the `COPY` statement copying the source.

### Stappen om te reproduceren / Steps to reproduce

 - Install `Podman`
 - Clone repository.
 - Run `podman build .` in the project directory.

### Verwacht gedrag / Expected behavior

Should build.

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by svenvandescheur**
Closes #2978

### CODE REVIEW

**Review by sergei-maertens — CHANGES_REQUESTED** [review]
If we're going to support podman, this needs a CI job that proves the failure and fix, otherwise we have no guarantees this won't be broken again accidentally in the future

**Comment by joeribekker** [comment]
> If we're going to support podman, this needs a CI job that proves the failure and fix, otherwise we have no guarantees this won't be broken again accidentally in the future

See my comment in the ticket.

In essence, we can make it podman compatible but we will not provide support on it. If desired, we can explicitely mention this in the documentation.

**Comment by sergei-maertens** [comment]
> > If we're going to support podman, this needs a CI job that proves the failure and fix, otherwise we have no guarantees this won't be broken again accidentally in the future
> 
> See my comment in the ticket.
> 
> In essence, we can make it podman compatible but we will not provide support on it. If desired, we can explicitely mention this (works but not supported) in the documentation.

agree - but I still want some automated guarantee that we can build with podman if we implement this patch. We do periodically restructure the dockerfiles according to new insights and this is definitely something that would break.

**Comment by sergei-maertens** [comment]
Closing this as we currently don't have any need for it, nor does the stakeholder anymore.

**Pull request closed without merging**
